# Generated by Django 2.1.5 on 2019-02-03 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_created=True)),
                ('tipo_movimento', models.CharField(choices=[('en', 'Entrada'), ('sd', 'Saída'), ('ce', 'Cancelamento de entrada'), ('cs', 'Cancelamento de saída')], default='sd', max_length=2)),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Movimento do estoque',
                'verbose_name_plural': 'Movimento do estoque',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=150)),
                ('minimo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.CategoriaProduto')),
            ],
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.Produto'),
        ),
    ]
