# Generated by Django 2.1.5 on 2019-02-03 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20190203_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='sku',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='data',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
