# Generated by Django 2.1.5 on 2019-02-04 03:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_movimentoestoque_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estoque.Local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estoque.Medida'),
            preserve_default=False,
        ),
    ]
