# Generated by Django 2.1.5 on 2019-02-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_auto_20190204_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medida',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
