# Generated by Django 2.1.5 on 2019-02-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_auto_20190204_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
