# Generated by Django 2.1.5 on 2019-02-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_categoriaproduto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
