# Generated by Django 2.1.5 on 2019-02-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_auto_20190204_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Já existe uma categoria cadastrada com este nome'}, max_length=50, unique=True),
        ),
    ]
