# Generated by Django 2.1.5 on 2019-02-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_auto_20190204_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoriaproduto',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoriaproduto',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Já existe uma categoria cadastrada com este nome'}, max_length=50, unique=True),
        ),
    ]
