# Generated by Django 2.1.5 on 2019-02-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_auto_20190204_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriaproduto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estoque.CategoriaProduto'),
        ),
    ]
