# Generated by Django 2.1.5 on 2019-02-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_auto_20190204_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriaproduto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.CategoriaProduto'),
        ),
        migrations.AlterField(
            model_name='subcategoriaproduto',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoriaproduto',
            unique_together={('nome', 'categoria')},
        ),
    ]
