# Generated by Django 2.1.5 on 2019-02-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_auto_20190204_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriaproduto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.CategoriaProduto'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('descricao', 'subcategoria')},
        ),
    ]
