# Generated by Django 2.1.5 on 2019-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_auto_20190205_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='motivo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
