# Generated by Django 2.1.5 on 2019-02-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_movimentoestoque_motivo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('codigo', 'subcategoria', 'local')},
        ),
    ]
