# Generated by Django 2.1.5 on 2019-02-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_auto_20190206_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('descricao', 'subcategoria', 'local')},
        ),
    ]
