# Generated by Django 2.1.5 on 2019-02-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0021_auto_20190206_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo_movimento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saída', 'Saída')], default='saída', max_length=2),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(error_messages={'unique': 'Já existe um produto cadastrado com este código'}, max_length=30, unique=True),
        ),
    ]
