# Generated by Django 2.1.5 on 2019-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_auto_20190206_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo_movimento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='saida', max_length=7),
        ),
    ]
