# Generated by Django 2.1.5 on 2019-02-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_auto_20190206_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoestoque',
            name='saldo_anterior',
            field=models.IntegerField(default=0),
        ),
    ]
